#ifndef TB_SVM_MODEL_H
#define TB_SVM_MODEL_H

#include "tb_svm.h" /* TB_SVM_N_FEATURES / TB_SVM_N_CLASSES */

/*
 * ============================ PLACEHOLDER MODEL ============================
 * Generated by:   (not yet — replace this file from the training notebook)
 * Trained on:     -
 * Dataset size:   -
 * Test accuracy:  -
 * Sensitivity:    -   (PKM target: accuracy >90%, sensitivity >95%)
 *
 * All weights are zero, so every class scores exactly its bias, all biases are
 * equal, and argmax always returns the first row: RED for any valid reading,
 * with confidence 0.25. This exists only so the firmware links and the flow can
 * be exercised end to end. IT DOES NOT TRIAGE. Replace before any real use.
 *
 * Export format from sklearn (LinearSVC + StandardScaler):
 *   K_MEAN / K_STD  <- scaler.mean_, scaler.scale_
 *   K_W             <- clf.coef_    shape (4, 5), row order = ui_priority_t
 *   K_B             <- clf.intercept_  shape (4,)
 * Row order MUST be RED, YELLOW, GREEN, BLACK (ui_priority_t declaration
 * order), not the LoRa wire order — tb_frame_priority_to_wire() converts.
 * ===========================================================================
 */

/* Feature order everywhere: hr, spo2, rr, bp_sys, bp_dia. */
static const float K_MEAN[TB_SVM_N_FEATURES] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
static const float K_STD[TB_SVM_N_FEATURES]  = {1.0f, 1.0f, 1.0f, 1.0f, 1.0f};

static const float K_W[TB_SVM_N_CLASSES][TB_SVM_N_FEATURES] = {
    {0.0f, 0.0f, 0.0f, 0.0f, 0.0f}, /* RED    */
    {0.0f, 0.0f, 0.0f, 0.0f, 0.0f}, /* YELLOW */
    {0.0f, 0.0f, 0.0f, 0.0f, 0.0f}, /* GREEN  */
    {0.0f, 0.0f, 0.0f, 0.0f, 0.0f}, /* BLACK  */
};

static const float K_B[TB_SVM_N_CLASSES] = {0.0f, 0.0f, 0.0f, 0.0f};

#endif /* TB_SVM_MODEL_H */
