#ifndef TB_SVM_H
#define TB_SVM_H

#include "ui_types.h"

/*
 * On-device triage inference: linear SVM, one-vs-rest over 4 classes.
 * Features are the physiological variables the PKM proposal names:
 * hr, spo2, rr, bp_sys, bp_dia. Age band and gender are collected by the UI
 * for victim registration but are NOT model inputs.
 *
 * Deterministic, no allocation, ~40 flops — safe to call from the LVGL task.
 * Weights live in tb_svm_model.h (generated by the offline training notebook).
 */

#define TB_SVM_N_FEATURES 5
#define TB_SVM_N_CLASSES  4

/*
 * Classify one vitals reading.
 *
 * Returns the winning ui_priority_t. *confidence (may be NULL) gets a softmax
 * over the class scores, always in [0,1] — the range the backend expects.
 *
 * If v->valid is false the readings are stale or missing: the result is
 * UI_PRIORITY_BLACK with confidence 0, because guessing a priority from
 * absent vitals is worse than reporting that we do not know.
 */
ui_priority_t tb_svm_classify(const vitals_t *v, float *confidence);

#endif /* TB_SVM_H */
