# TEMPORARY probe file (Editor normally generates this on export)
list(APPEND LV_EDITOR_PROJECT_SOURCES
    ${CMAKE_CURRENT_LIST_DIR}/images/icon_home_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/wifi_high_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/unlock_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/bell_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/chevron_up_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/arrow_up_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/icon_lock_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/icon_mail_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/icon_wifi_high_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/icon_play_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/icon_power_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/icon_check_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/icon_heart_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/icon_arrow_right_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/icon_download_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/check_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/power_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/icon_edit_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/icon_sun_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/heart_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/arrow_right_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/icon_moon_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/icon_chevron_right_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/close_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/icon_calendar_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/user_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/icon_plus_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/icon_wifi_low_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/icon_close_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/icon_wifi_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/icon_bluetooth_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/sun_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/icon_info_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/icon_chevron_left_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/bluetooth_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/icon_star_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/chevron_right_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/icon_chevron_up_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/icon_battery_full_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/icon_chevron_down_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/icon_unlock_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/menu_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/settings_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/volume_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/arrow_left_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/clock_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/edit_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/camera_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/chevron_left_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/arrow_down_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/icon_clock_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/battery_full_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/chevron_down_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/play_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/icon_settings_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/lock_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/mail_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/icon_refresh_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/signal_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/pause_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/icon_bell_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/calendar_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/trash_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/refresh_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/wifi_low_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/icon_upload_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/home_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/icon_trash_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/icon_pause_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/search_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/icon_menu_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/minus_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/icon_search_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/icon_wifi_zero_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/upload_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/star_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/download_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/icon_minus_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/icon_signal_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/info_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/wifi_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/wifi_zero_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/icon_arrow_left_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/battery_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/icon_volume_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/icon_arrow_up_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/icon_user_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/icon_arrow_down_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/plus_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/icon_battery_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/moon_data.c
    ${CMAKE_CURRENT_LIST_DIR}/images/icon_camera_data.c
    ${CMAKE_CURRENT_LIST_DIR}/screens/screen_components_gen.c
    ${CMAKE_CURRENT_LIST_DIR}/components/layout/base_box/base_box_gen.c
    ${CMAKE_CURRENT_LIST_DIR}/components/layout/panel/panel_gen.c
    ${CMAKE_CURRENT_LIST_DIR}/components/layout/column/column_gen.c
    ${CMAKE_CURRENT_LIST_DIR}/components/layout/container/container_gen.c
    ${CMAKE_CURRENT_LIST_DIR}/components/layout/row/row_gen.c
    ${CMAKE_CURRENT_LIST_DIR}/components/controls/dropdown/dropdown_gen.c
    ${CMAKE_CURRENT_LIST_DIR}/components/controls/text_box/text_box_gen.c
    ${CMAKE_CURRENT_LIST_DIR}/components/controls/checkbox/checkbox_gen.c
    ${CMAKE_CURRENT_LIST_DIR}/components/controls/slider/slider_gen.c
    ${CMAKE_CURRENT_LIST_DIR}/components/controls/button/button_gen.c
    ${CMAKE_CURRENT_LIST_DIR}/components/controls/text_input/text_input_gen.c
    ${CMAKE_CURRENT_LIST_DIR}/components/controls/switch/switch_gen.c
    ${CMAKE_CURRENT_LIST_DIR}/components/controls/bar/bar_gen.c
    ${CMAKE_CURRENT_LIST_DIR}/components/controls/arc/arc_gen.c
    ${CMAKE_CURRENT_LIST_DIR}/components/controls/keyboard/keyboard_gen.c
    ${CMAKE_CURRENT_LIST_DIR}/components/list/list_section/list_section_gen.c
    ${CMAKE_CURRENT_LIST_DIR}/components/list/list/list_gen.c
    ${CMAKE_CURRENT_LIST_DIR}/components/list/list_item/list_item_gen.c
    ${CMAKE_CURRENT_LIST_DIR}/components/list/list_separator/list_separator_gen.c
    ${CMAKE_CURRENT_LIST_DIR}/components/typography/h2/h2_gen.c
    ${CMAKE_CURRENT_LIST_DIR}/components/typography/h5/h5_gen.c
    ${CMAKE_CURRENT_LIST_DIR}/components/typography/h4/h4_gen.c
    ${CMAKE_CURRENT_LIST_DIR}/components/typography/h3/h3_gen.c
    ${CMAKE_CURRENT_LIST_DIR}/components/typography/h1/h1_gen.c
    ${CMAKE_CURRENT_LIST_DIR}/components/typography/text/text_gen.c
    ${CMAKE_CURRENT_LIST_DIR}/fonts/font_h5_data.c
    ${CMAKE_CURRENT_LIST_DIR}/fonts/font_body_symbols__data.c
    ${CMAKE_CURRENT_LIST_DIR}/fonts/font_h5__data.c
    ${CMAKE_CURRENT_LIST_DIR}/fonts/font_h3_data.c
    ${CMAKE_CURRENT_LIST_DIR}/fonts/font_h1_data.c
    ${CMAKE_CURRENT_LIST_DIR}/fonts/font_body__data.c
    ${CMAKE_CURRENT_LIST_DIR}/fonts/font_h4__data.c
    ${CMAKE_CURRENT_LIST_DIR}/fonts/font_body_small_data.c
    ${CMAKE_CURRENT_LIST_DIR}/fonts/font_h1__data.c
    ${CMAKE_CURRENT_LIST_DIR}/fonts/font_h4_data.c
    ${CMAKE_CURRENT_LIST_DIR}/fonts/font_body_data.c
    ${CMAKE_CURRENT_LIST_DIR}/fonts/font_body_symbols_data.c
    ${CMAKE_CURRENT_LIST_DIR}/fonts/font_h2_data.c
    ${CMAKE_CURRENT_LIST_DIR}/fonts/font_h2__data.c
    ${CMAKE_CURRENT_LIST_DIR}/fonts/font_h3__data.c
)
